### ISSUE TITLE
[ERROR] dagger::client - timeout syncing with peer

### ISSUE THREAD

**Issue by StoneMac65** [GenesysGo/dagger-testnet-issues#13] opened 2024-01-07 03:46 UTC
My node stopped syncing after 24 hours of running with no issues. I share the logs for the pas 24 hours, hopefully it helps to find the root cause
[config.zip](https://github.com/GenesysGo/dagger-testnet-issues/files/13852155/config.zip)

**Comment by StoneMac65** [comment] 2024-01-07 03:50
[config.zip](https://github.com/GenesysGo/dagger-testnet-issues/files/13852154/config.zip)

**Comment by tracy-codes** [comment] 2024-02-02 23:19
Closing as a duplicate of #4

**Closed as completed by tracy-codes** 2024-02-02 23:19 UTC
