### ISSUE TITLE
[ERROR] log_panics - thread 'controller' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"

### ISSUE THREAD

**Issue by g-scooter** [GenesysGo/dagger-testnet-issues#70] opened 2024-03-02 17:51 UTC
**Describe the bug**
[ERROR] log_panics - thread 'controller' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)" after several seconds of:
[ERROR] dagger::p2p::graph::event - Failed to save event in database: IO error: While open a file for random read: /mnt/dag/historydb/126428.sst: Too many open files

See 2024-03-01T23:55:28.528734930 for first ERROR. Finalization continues for about 10 seconds then panic at 2024-03-01T23:55:40.852116704

[event_log_2024-03-01_23-56-02.log](https://github.com/GenesysGo/dagger-testnet-issues/files/14470263/event_log_2024-03-01_23-56-02.log)

**Comment by tracy-codes** [comment] 2024-03-02 20:30
Duplicate of #69

**Closed as not planned** 2024-03-02 20:30 UTC
