### ISSUE TITLE
Node stopped syncing

### ISSUE THREAD

**Issue by armaanarvind** [GenesysGo/dagger-testnet-issues#12] opened 2024-01-07 03:13 UTC
[configlog.txt.zip](https://github.com/GenesysGo/dagger-testnet-issues/files/13852099/configlog.txt.zip)
**Describe the bug**
The node stopped syncing with peers and errors were thrown. Resolved this issue by restarting the node. 
PFA, log file.

**To Reproduce**
Can't reproduce at my end as I'm not sure how it happened. I've highlighted this issue in discord and was asked to load the config file. possible explaination is epoch boundary related.

**Comment by tracy-codes** [comment] 2024-02-02 23:19
Closing as a duplicate of #4

**Closed as completed by tracy-codes** 2024-02-02 23:19 UTC
